server:
  port: ${port:9003}

spring:
  application:
    name: message-service

  zipkin:
    base-url: http://127.0.0.1:9411
    enabled: true

  sleuth:
    sampler:
      probability: 1.0

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: "jdbc:mysql://localhost:3306/messageservicedb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: Jerrytran97@
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

  security:
    enabled: false
